---
- name: Init
  hosts: all
  tasks:
    - name: Install Docker
      become: true
      import_role:
        name: geerlingguy.docker

    - name: Install Docker Module for Python
      become: true
      import_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker==6.1.3
          - name: docker-compose

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: adding ubuntu to docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create work directory
      become: true
      ansible.builtin.file:
        path: /work
        state: directory
        mode: '0755'

    - name: Copy Docker Compose file
      become: true
      ansible.builtin.copy:
        src: ./node_exporter/docker-compose.yaml
        dest: /work/node_exporter/

    - name: Launch Docker Compose containers
      become: true
      docker_compose:
        files:
          - docker-compose.yaml
        project_src: /work/node_exporter
#        state: present
#      vars:
#        ansible_python_interpreter: /bin/python3

