global:
  scrape_interval: 15s
  scrape_timeout:
  evaluation_interval: 15s

scrape_configs:
# сам prometheus будет собирать о себе метрики
- job_name: prometheus
  scrape_interval: 15s
  static_configs:
  - targets: ['localhost:9090']

# будет получать метрики, предоставляемые node exporter
- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets: ['node_exporter:9100']

- job_name: "cadvisor"
  scrape_interval: 5s
  static_configs:
  - targets: ['cadvisor:8080']
