global:
  scrape_interval: 15s
  scrape_timeout:
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout:
    api_version: v1
scrape_configs:
# сам prometheus будет собирать о себе метрики
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
# будет получать метрики, предоставляемые node exporter
- job_name: node_exporter_service
  static_configs:
  - targets: ['192.168.1.110:9100']
